ProjetoAula1CoreMVC/Aula01/Models/ErrorViewModel.cs
namespace Aula01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoAula1CoreMVC/Aula01/Models/Filme.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Aula01.Models
{
    public class Filme
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo Título é obrigatório")]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "O Título precisar ter entre 3 ou 60 caracteres")]
        public string Titulo { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Data em formato incorreto")]
        [Required(ErrorMessage = "O campo Data de Lançamento é obrigatório")]
        [Display(Name = "Data de Lançamento")]
        public DateTime DataLancamento { get; set; }

        //[RegularExpression(@"^[A-Z]+[a-zA-Z\uc00C0- \u00FF""'\w-]*$", ErrorMessage = "Genero em formato inválido")]
        [StringLength(30, ErrorMessage = "Máximo de 30 caracteres"), Required(ErrorMessage = "O campo genero é requirido")]
        public string Genero { get; set; }


        [Range(1, 1000, ErrorMessage = "Valor de 1 a 1000")]
        [Required(ErrorMessage = "Preencha o campo valor")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Valor { get; set; }

        [Required(ErrorMessage = "Preencha o campo Avaliação")]
        [Display(Name = "Avaliação")]
        [RegularExpression(@"^[0-5]*$", ErrorMessage = "Somente números")]
        public int Avaliacao { get; set; }
    }
}

ProjetoAula1CoreMVC/Aula01/Controllers/FilmesController.cs
using Aula01.Models;
using Microsoft.AspNetCore.Mvc;

namespace Aula01.Controllers
{
    public class FilmesController : Controller
    {
        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Adicionar(Filme filme)
        {
            if (ModelState.IsValid)
            {

            }

            return View(filme);
        }
    }
}

ProjetoAula1CoreMVC/Aula01/Controllers/HomeController.cs
using System.Diagnostics;
using Aula01.Models;
using Microsoft.AspNetCore.Mvc;

namespace Aula01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoAula1CoreMVC/Aula01/ViewComponents/CarrinhoViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Aula01.ViewComponents
{
    [ViewComponent(Name = "Carrinho")]
    public class CarrinhoViewComponent : ViewComponent
    {
        public int ItensCarrinho { get; set; }

        public CarrinhoViewComponent()
        {
            ItensCarrinho = 3;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(ItensCarrinho);
        }
    }
}

ProjetoAula1CoreMVC/Aula01/Views/Filmes/Adicionar.cshtml
@model Aula01.Models.Filme

@{
	ViewData["Title"] = "Adicionar novo Filme";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
	<div class="col-md-4">

		<form asp-action="Adicionar"> 

			<div asp-validation-summary="All" class="text-danger"></div>

			<div class="form-group">
				<label asp-for="Titulo" class="control-label"></label>
				<input asp-for="Titulo" class="form-control" />
				<span asp-validation-for="Avaliacao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="DataLancamento" class="control-label"></label>
				<input asp-for="DataLancamento" class="form-control" />
				<span asp-validation-for="Avaliacao" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Genero" class="control-label"></label>
				<input asp-for="Genero" class="form-control" />
				<span asp-validation-for="Avaliacao" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Valor" class="control-label"></label>
				<input asp-for="Valor" class="form-control" />
				<span asp-validation-for="Avaliacao" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Avaliacao" class="control-label"></label>
				<input asp-for="Avaliacao" class="form-control" />
				<span asp-validation-for="Avaliacao" class="text-danger"></span>
			</div>

			<div class="form-group">
				<input type="submit" value="Adicionar" class="btn btn-primary" />
			</div>

		</form>

	</div>
</div>


@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoAula1CoreMVC/Aula01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetoAula1CoreMVC/Aula01/Views/Shared/Components/Default.cshtml
@model int

<span class="fa fa-shopping-cart fa-2x">@Model</span>

ProjetoAula1CoreMVC/Aula01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aula01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Aula01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aula01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes" asp-action="Adicionar">Filmes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Aula01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>